[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'

[phases.setup]
    nixPkgs = ['nodejs', 'jq']

[phases.install]
    cmds = ['npm install']

[phases.build]
    cmds = ['npm run build:ssr']

[start]
    cmd = 'node dist/llantatech/server/main.js'
