name: Deploy Compodoc to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Compodoc
        run: npm run docs

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=docs/compodoc --branch=gh-pages --base-href=/RutaKids-WebApp/Documentation/
